language: php

php:
  - 7.0

env:
  global:
    - setup=basic
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=SomeRandomStringSomeRandomString

before_script:
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update -q
  - sudo apt-get install -y imagemagick
  - printf "\n" | pecl install imagick
  - composer selfupdate
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml;
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - vendor/bin/coveralls
